name: veyra
description: Veyra - plugin-based wallpaper aggregator
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State
  provider: ^6.1.2

  # Network
  dio: ^5.4.3

  # Storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2

  # Pack import (zip/enginepack)
  file_picker: ^8.1.2
  archive: ^3.6.1

  # UI
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0

  # JS runtime (do NOT rely on fetch; we use our protocol)
  flutter_js: ^0.8.5
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  shimmer: ^3.0.0
  animations: ^2.1.1
  flutter_code_editor: ^0.3.1
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.10.5
  injectable_generator: ^2.12.0

flutter:
  uses-material-design: true
  generate: true